# Generated by Django 4.2.5 on 2023-12-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerInterface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
